Writing_Studio/Writing_Studio/Controllers/FileUploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;


namespace Writing_Studio.Controllers
{
    public class FileUploadController : Controller
    {
        // GET: FileUpload
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
           
            
                    if (file != null)
                    {
                        string FileName = Path.GetFileName(file.FileName);
                        string path = Server.MapPath("~/Content/Profile1.jpg");
                        file.SaveAs(path);
                    }
                    ViewBag.FileStatus = "File uploaded successfully.";
                
            
            
            return View("Index");
        }
    }
}

Writing_Studio/Writing_Studio/Views/FileUpload/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <meta name="viewport" content="width-device-width"/>
</head>
<body>
    <div>
        <center>
            @using (Html.BeginForm("Index", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <input type="file" name="File" id="File" />
                <input type="submit" value="Upload" />
            }

        </center>
    </div>
    <a href="@Url.Action("Profile","Account")" class="btn btn-default elements">Back &raquo;</a>
</body>